### ISSUE TITLE
How to run this program's mobility model

### ISSUE THREAD

**Issue by mikewang2000** [Zihao-Howard-Zhou/Simulation-Platform-for-UAV-network#5]
When I run main.py, the program only generates a static position map, and the program prints only the init coordinates of the 15 UAVs.

So How to run this program's mobility model.

Thank you

**Comment by Zihao-Howard-Zhou** [comment]
When you run "main.py", the program will first plot the initial position distribution of the UAVs, then you need to close this window, and then the program will continue to run, when the simulation time is over, the final position distribution of the UAVs will be plotted. If you need to see the trajectory of the UAV, you can go to the corresponding mobility model, for example the 3D random walk model, and you can find "self.my_drone.simulator.env.process(self.show_trajectory())".
